# Generated by Django 4.1 on 2022-08-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expenses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("description", models.CharField(max_length=255)),
                ("amount", models.DecimalField(decimal_places=20, max_digits=20)),
            ],
        ),
    ]
