# Generated by Django 4.1 on 2022-08-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0004_remove_expenses_category_name_expenses_category_opt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="category_opt",
            field=models.CharField(
                choices=[
                    ("F", "Food"),
                    ("H", "Health"),
                    ("E", "Education"),
                    ("H", "Home"),
                    ("O", "Other"),
                ],
                default="O",
                max_length=1,
                verbose_name="category",
            ),
        ),
    ]
