# Generated by Django 4.1 on 2022-08-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0005_alter_expenses_category_opt"),
    ]

    operations = [
        migrations.RemoveField(model_name="expenses", name="category_opt",),
        migrations.AddField(
            model_name="expenses",
            name="category",
            field=models.CharField(
                choices=[
                    ("F", "Food"),
                    ("H", "Health"),
                    ("E", "Education"),
                    ("H", "Home"),
                    ("O", "Other"),
                ],
                default="O",
                max_length=1,
            ),
        ),
    ]
