# Generated by Django 4.1 on 2022-08-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0007_alter_expenses_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="category",
            field=models.CharField(
                choices=[
                    ("Food", "Food"),
                    ("H", "Health"),
                    ("T", "Travel"),
                    ("E", "Education"),
                    ("H", "Home"),
                    ("O", "Other"),
                ],
                default="O",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="expenses", name="date", field=models.DateField(),
        ),
    ]
