# Generated by Django 4.1 on 2022-08-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CategoryAPI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_type",
                    models.CharField(
                        choices=[
                            ("Food", "Food"),
                            ("Health", "Health"),
                            ("Education", "Education"),
                            ("Home", "Home"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
