# Generated by Django 4.1 on 2022-08-12 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryapi",
            name="category_type",
            field=models.CharField(
                choices=[
                    ("F", "Food"),
                    ("H", "Health"),
                    ("E", "Education"),
                    ("H", "Home"),
                    ("O", "Other"),
                ],
                default="O",
                max_length=1,
            ),
        ),
    ]
