# Generated by Django 4.1 on 2022-08-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_alter_categoryapi_category_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryapi",
            name="category_type",
            field=models.CharField(
                choices=[
                    ("Food", "Food"),
                    ("H", "Health"),
                    ("T", "Travel"),
                    ("E", "Education"),
                    ("H", "Home"),
                    ("O", "Other"),
                ],
                default="O",
                max_length=10,
            ),
        ),
    ]
