# Generated by Django 4.1 on 2022-08-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0003_alter_categoryapi_category_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryapi",
            name="category_type",
            field=models.CharField(
                choices=[
                    ("Food", "Food"),
                    ("Health", "Health"),
                    ("Travel", "Travel"),
                    ("Education", "Education"),
                    ("Home", "Home"),
                    ("Other", "Other"),
                ],
                default="Other",
                max_length=10,
            ),
        ),
    ]
