# Generated by Django 4.1 on 2022-08-15 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("income", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="income",
            name="amount",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="income", name="date", field=models.DateField(),
        ),
    ]
